package com.vserve.project.enums;

public enum Category {
    OLD_AGE_HOME,
    PUBLIC_SERVICE ,
    DISASTER_MANAGEMENT,
    EMERGENCY,
    TEACHING,
    AWARENESS,
    HEALTHCARE,
    FOOD_SERVICES,
    CLEANLINESS_DRIVE,
    EVENT_MANAGEMENT,
    LOGISTICS,
    MEDIA_AND_CONTENT,
    IT_SUPPORT,
    DATA_MANAGEMENT,
    FUNDRAISING,
    COMMUNITY_SUPPORT,
    ARTS_AND_CULTURE,
    SOCIAL_WORK,
    ENVIRONMENT,
    CHILD_CARE,
    WOMEN_EMPOWERMENT,
    ANIMAL_WELFARE,
    RURAL_DEVELOPMENT,
    SKILL_DEVELOPMENT,
    ADMIN_SUPPORT,
    OTHER

    }
