spring.application.name=${APP_NAME:project}

spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/v_serve?autoReconnect=true&useSSL=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:3W1NsVxTdbBzF3j.root}
spring.datasource.password=${DB_PASSWORD:v5BEnE9fNjz6E7Qd}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.hikari.maximum-pool-size=5

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:vserve.community@gmail.com}
spring.mail.password=${MAIL_PASSWORD:xgmpuxakjyooquai}
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# IMPORTANT ? SSL (NOT START TLS)
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Spring Security
# spring.security.user.name=admin
# spring.security.user.password=123

# Custom Keys
csc-api.key=${CSC_API_KEY:c8eb874f7ce66702d1f69b45f2613adc322852e2fd41df3a20494cde78546408}
csc-api.url=${CSC_API_URL:https://api.countrystatecity.in/v1}


#app.ai.embedding.url=http://localhost:8001/embedding
app.ai.embedding.url=${AI_EMBEDDING_URL:https://vservecommunity-ai-embedding-service.hf.space/embedding}
app.mail=${APP_MAIL:vserve.community@gmail.com}


app.frontend.url= ${FRONTEND_URL:http://localhost:5173}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# MOST IMPORTANT
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1